### PR TITLE
B miller

### PR DESCRIPTION
**Pull request by BruceAlanMiller**

### CODE REVIEW

**Review by FreetimeFM — CHANGES_REQUESTED** [review]
Don't add Sprint 1/questionnaire1.php

**Review by MikolajOlejnik — APPROVED** [review]
Product backlog descriptions sound good.

**Comment by BruceAlanMiller** [comment]
will remove, questionnaire1 from sprint 1 folder of  this branch

**Comment by FreetimeFM** [comment]
I did that for you

**Comment by BruceAlanMiller** [comment]
redundant files have been removed

**Review by FreetimeFM — APPROVED** [review]
Looks good

**Pull request merged**
