### PR TITLE
Updated php

### PR DESCRIPTION
**Pull request by FreetimeFM**
Added more more php functionality to the questionnaire form.

Edit:
This pull request also adds custom bootstrap css, the questionnaire html and the php files.
FYI, the submission for the multi_select questions still doesn't work.

### CODE REVIEW

**Comment by FreetimeFM** [comment]
This pull request also adds custom bootstrap css, the questionnaire html and the php files.
FYI, the submission for the multi_select questions still doesn't work.

**Review by MikolajOlejnik — APPROVED** [review]
PHP is in progress.

**Comment by FreetimeFM** [comment]
Temporarily closed it so that momchilWebsite branch merged to master before this branch.

**Comment by FreetimeFM** [comment]
Momchila website branch merged, reopening this one

**Pull request merged**
