### PR TITLE
Updated php to get multi_select options to submit.

### PR DESCRIPTION
**Pull request by FreetimeFM**
Updated php to get multi_select options to submit to the db and other minor changes.

### CODE REVIEW

**Review by jordankeiller — APPROVED** [review]
Looks great, good job.

**Comment by FreetimeFM** [comment]
Don't merge yet

**Comment by FreetimeFM** [comment]
Added participant query fix

**Review by mbadzhev — APPROVED** [review]

**Comment by mbadzhev** [comment]
Everything looks good, no merge conflict either.

**Pull request merged**
